project:
  type: book

book:
  title: "sec-reference-reprex"
  author: "Jane Doe"
  date: "4/15/2022"
  chapters:
    - index.qmd
    - part: intro.qmd
      chapters:
        - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

